// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de_DE": &dictionary{index: de_DEIndex, data: de_DEData},
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"All Services and Projects":       10,
	"Battery Disposal":                36,
	"Cancellation Policy":             4,
	"Cash":                            6,
	"Cash by mail":                    38,
	"Cash by mail in 20 currencies":   7,
	"Cash payment in local store":     37,
	"Cash payment in our store":       31,
	"Concept":                         33,
	"Contact & News":                  17,
	"Contact us":                      18,
	"DHL parcel, franked digitally":   29,
	"DHL parcel, franked handwritten": 28,
	"Delivery":                        25,
	"Digital Goods":                   13,
	"Germany":                         19,
	"Got an idea or found an error? Drop us a note!": 24,
	"Imprint":                               3,
	"Legal":                                 0,
	"Local Store":                           12,
	"Mon+Thu 2pm-6pm":                       21,
	"Monero and Bitcoin":                    8,
	"Online printing":                       16,
	"Online shop":                           14,
	"Opening hours":                         20,
	"Order Service":                         15,
	"PayPal":                                32,
	"Payment":                               5,
	"Pickup from locker in our local store": 27,
	"Pickup in our local store":             26,
	"Privacy policy":                        2,
	"SEPA bank transfer":                    9,
	"See here for short-term changes":       23,
	"Support us":                            34,
	"Terms and Conditions":                  1,
	"Tue+Wed+Fri+Sat 10am-2pm":              22,
	"UPS parcel directly from our contractor": 30,
	"Why?": 11,
	"myflexbox Locker via DPD (Germany only)": 35,
}

var de_DEIndex = []uint32{ // 40 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000c, 0x00000010, 0x0000001c,
	0x00000026, 0x00000039, 0x00000043, 0x0000004b,
	0x0000006d, 0x00000080, 0x00000092, 0x000000ad,
	0x000000b4, 0x000000c3, 0x000000d3, 0x000000de,
	0x000000ed, 0x000000fd, 0x0000010c, 0x00000114,
	0x00000120, 0x00000130, 0x00000140, 0x00000156,
	0x0000017e, 0x000001a1, 0x000001a9, 0x000001c4,
	0x000001f0, 0x00000214, 0x00000230, 0x00000253,
	// Entry 20 - 3F
	0x00000270, 0x00000277, 0x0000027f, 0x00000290,
	0x000002c1, 0x000002e1, 0x000002fe, 0x0000030f,
} // Size: 184 bytes

const de_DEData string = "" + // Size: 783 bytes
	"\x02Rechtliches\x02AGB\x02Datenschutz\x02Impressum\x02Widerrufsbelehrung" +
	"\x02Bezahlung\x02Bargeld\x02Bargeld per Post in 20 Währungen\x02Monero u" +
	"nd Bitcoin\x02SEPA-Überweisung\x02Alle Angebote und Projekte\x02Warum?" +
	"\x02Ladengeschäft\x02Digitale Güter\x02Onlineshop\x02Bestellservice\x02O" +
	"nlinedruckerei\x02Kontakt & News\x02Kontakt\x02Deutschland\x02Öffnungsze" +
	"iten\x02Mo+Do 14-18 Uhr\x02Di+Mi+Fr+Sa 10-14 Uhr\x02Sieh hier für kurzfr" +
	"istige Änderungen\x02Fehler oder Hinweise? Schreib uns!\x02Versand\x02Ab" +
	"holung im Ladengeschäft\x02Abholung aus Schließfach im Ladengeschäft\x02" +
	"DHL-Paket handschriftlich frankiert\x02DHL-Paket digital frankiert\x02UP" +
	"S-Paket direkt von der Druckerei\x02Barzahlung im Ladengeschäft\x02PayPa" +
	"l\x02Konzept\x02Unterstütze uns\x02myflexbox-Abholautomat via DPD (nur D" +
	"eutschland)\x02Hinweise zur Batterieentsorgung\x02Barzahlung im Ladenges" +
	"chäft\x02Bargeld per Post"

var en_USIndex = []uint32{ // 40 elements
	// Entry 0 - 1F
	0x00000000, 0x00000006, 0x0000001b, 0x0000002a,
	0x00000032, 0x00000046, 0x0000004e, 0x00000053,
	0x00000071, 0x00000084, 0x00000097, 0x000000b1,
	0x000000b6, 0x000000c2, 0x000000d0, 0x000000dc,
	0x000000ea, 0x000000fa, 0x00000109, 0x00000114,
	0x0000011c, 0x0000012a, 0x0000013a, 0x00000153,
	0x00000173, 0x000001a2, 0x000001ab, 0x000001c5,
	0x000001eb, 0x0000020b, 0x00000229, 0x00000251,
	// Entry 20 - 3F
	0x0000026b, 0x00000272, 0x0000027a, 0x00000285,
	0x000002ad, 0x000002be, 0x000002da, 0x000002e7,
} // Size: 184 bytes

const en_USData string = "" + // Size: 743 bytes
	"\x02Legal\x02Terms and Conditions\x02Privacy policy\x02Imprint\x02Cancel" +
	"lation Policy\x02Payment\x02Cash\x02Cash by mail in 20 currencies\x02Mon" +
	"ero and Bitcoin\x02SEPA bank transfer\x02All Services and Projects\x02Wh" +
	"y?\x02Local Store\x02Digital Goods\x02Online shop\x02Order Service\x02On" +
	"line printing\x02Contact & News\x02Contact us\x02Germany\x02Opening hour" +
	"s\x02Mon+Thu 2pm-6pm\x02Tue+Wed+Fri+Sat 10am-2pm\x02See here for short-t" +
	"erm changes\x02Got an idea or found an error? Drop us a note!\x02Deliver" +
	"y\x02Pickup in our local store\x02Pickup from locker in our local store" +
	"\x02DHL parcel, franked handwritten\x02DHL parcel, franked digitally\x02" +
	"UPS parcel directly from our contractor\x02Cash payment in our store\x02" +
	"PayPal\x02Concept\x02Support us\x02myflexbox Locker via DPD (Germany onl" +
	"y)\x02Battery Disposal\x02Cash payment in local store\x02Cash by mail"

	// Total table size 1894 bytes (1KiB); checksum: D0FA265E
